// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fuse/loop/v1/loop.proto

// Package fuse.loop.v1 is the IDL-defined loop.* wire for the networked binding
// (change 0055), successor to the JSON-over-WebSocket wire (#48, ADR-0032
// superseded). It exposes loop control — StartLoop / Send (unary) and Observe
// (server-streaming history-then-live) — as a Connect service so a browser can
// reach it over HTTP/2 with no proxy. Tenant is a typed, pass-through request
// field (identity enforcement is #0049). The per-kind payload shapes are NOT
// re-modeled here: payload stays raw JSON bytes (#50 owns SDK ergonomics), and
// kind stays a string to avoid lock-stepping a proto enum with internal/event.Kind.
package loopv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ethanhinson/fuse/internal/loopwire/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LoopServiceName is the fully-qualified name of the LoopService service.
	LoopServiceName = "fuse.loop.v1.LoopService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LoopServiceStartLoopProcedure is the fully-qualified name of the LoopService's StartLoop RPC.
	LoopServiceStartLoopProcedure = "/fuse.loop.v1.LoopService/StartLoop"
	// LoopServiceSendProcedure is the fully-qualified name of the LoopService's Send RPC.
	LoopServiceSendProcedure = "/fuse.loop.v1.LoopService/Send"
	// LoopServiceObserveProcedure is the fully-qualified name of the LoopService's Observe RPC.
	LoopServiceObserveProcedure = "/fuse.loop.v1.LoopService/Observe"
)

// LoopServiceClient is a client for the fuse.loop.v1.LoopService service.
type LoopServiceClient interface {
	// StartLoop constructs and drives one agent loop, returning its loop_id.
	StartLoop(context.Context, *connect.Request[v1.StartLoopRequest]) (*connect.Response[v1.StartLoopResponse], error)
	// Send injects human input at the loop's next turn boundary.
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	// Observe streams history since from_seq then live events; a reconnecting client
	// re-opens it from its last-seen seq (the WS-era Attach/HTTP-replay role).
	Observe(context.Context, *connect.Request[v1.ObserveRequest]) (*connect.ServerStreamForClient[v1.ObserveEvent], error)
}

// NewLoopServiceClient constructs a client for the fuse.loop.v1.LoopService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLoopServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LoopServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	loopServiceMethods := v1.File_fuse_loop_v1_loop_proto.Services().ByName("LoopService").Methods()
	return &loopServiceClient{
		startLoop: connect.NewClient[v1.StartLoopRequest, v1.StartLoopResponse](
			httpClient,
			baseURL+LoopServiceStartLoopProcedure,
			connect.WithSchema(loopServiceMethods.ByName("StartLoop")),
			connect.WithClientOptions(opts...),
		),
		send: connect.NewClient[v1.SendRequest, v1.SendResponse](
			httpClient,
			baseURL+LoopServiceSendProcedure,
			connect.WithSchema(loopServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		observe: connect.NewClient[v1.ObserveRequest, v1.ObserveEvent](
			httpClient,
			baseURL+LoopServiceObserveProcedure,
			connect.WithSchema(loopServiceMethods.ByName("Observe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// loopServiceClient implements LoopServiceClient.
type loopServiceClient struct {
	startLoop *connect.Client[v1.StartLoopRequest, v1.StartLoopResponse]
	send      *connect.Client[v1.SendRequest, v1.SendResponse]
	observe   *connect.Client[v1.ObserveRequest, v1.ObserveEvent]
}

// StartLoop calls fuse.loop.v1.LoopService.StartLoop.
func (c *loopServiceClient) StartLoop(ctx context.Context, req *connect.Request[v1.StartLoopRequest]) (*connect.Response[v1.StartLoopResponse], error) {
	return c.startLoop.CallUnary(ctx, req)
}

// Send calls fuse.loop.v1.LoopService.Send.
func (c *loopServiceClient) Send(ctx context.Context, req *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return c.send.CallUnary(ctx, req)
}

// Observe calls fuse.loop.v1.LoopService.Observe.
func (c *loopServiceClient) Observe(ctx context.Context, req *connect.Request[v1.ObserveRequest]) (*connect.ServerStreamForClient[v1.ObserveEvent], error) {
	return c.observe.CallServerStream(ctx, req)
}

// LoopServiceHandler is an implementation of the fuse.loop.v1.LoopService service.
type LoopServiceHandler interface {
	// StartLoop constructs and drives one agent loop, returning its loop_id.
	StartLoop(context.Context, *connect.Request[v1.StartLoopRequest]) (*connect.Response[v1.StartLoopResponse], error)
	// Send injects human input at the loop's next turn boundary.
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	// Observe streams history since from_seq then live events; a reconnecting client
	// re-opens it from its last-seen seq (the WS-era Attach/HTTP-replay role).
	Observe(context.Context, *connect.Request[v1.ObserveRequest], *connect.ServerStream[v1.ObserveEvent]) error
}

// NewLoopServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLoopServiceHandler(svc LoopServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	loopServiceMethods := v1.File_fuse_loop_v1_loop_proto.Services().ByName("LoopService").Methods()
	loopServiceStartLoopHandler := connect.NewUnaryHandler(
		LoopServiceStartLoopProcedure,
		svc.StartLoop,
		connect.WithSchema(loopServiceMethods.ByName("StartLoop")),
		connect.WithHandlerOptions(opts...),
	)
	loopServiceSendHandler := connect.NewUnaryHandler(
		LoopServiceSendProcedure,
		svc.Send,
		connect.WithSchema(loopServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	loopServiceObserveHandler := connect.NewServerStreamHandler(
		LoopServiceObserveProcedure,
		svc.Observe,
		connect.WithSchema(loopServiceMethods.ByName("Observe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fuse.loop.v1.LoopService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LoopServiceStartLoopProcedure:
			loopServiceStartLoopHandler.ServeHTTP(w, r)
		case LoopServiceSendProcedure:
			loopServiceSendHandler.ServeHTTP(w, r)
		case LoopServiceObserveProcedure:
			loopServiceObserveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLoopServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLoopServiceHandler struct{}

func (UnimplementedLoopServiceHandler) StartLoop(context.Context, *connect.Request[v1.StartLoopRequest]) (*connect.Response[v1.StartLoopResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fuse.loop.v1.LoopService.StartLoop is not implemented"))
}

func (UnimplementedLoopServiceHandler) Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fuse.loop.v1.LoopService.Send is not implemented"))
}

func (UnimplementedLoopServiceHandler) Observe(context.Context, *connect.Request[v1.ObserveRequest], *connect.ServerStream[v1.ObserveEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("fuse.loop.v1.LoopService.Observe is not implemented"))
}
