package loopv1_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
)

// TestGeneratedStubsHaveNoDrift is the generate-and-commit drift guard: it re-runs
// `buf generate` into a throwaway output tree and asserts the freshly generated Go +
// TS stubs are byte-identical to the committed ones. If someone edits loop.proto and
// forgets to regenerate (or the pinned plugins move), this goes RED.
//
// It SKIPS when the buf toolchain is not on PATH (a plain `go test ./...` without the
// codegen toolchain installed still passes); CI that owns the wire contract installs
// buf + the plugins so the guard is live there.
func TestGeneratedStubsHaveNoDrift(t *testing.T) {
	if _, err := exec.LookPath("buf"); err != nil {
		t.Skip("buf not on PATH; drift guard needs the codegen toolchain (skipping)")
	}
	if _, err := exec.LookPath("protoc-gen-go"); err != nil {
		t.Skip("protoc-gen-go not on PATH; skipping drift guard")
	}

	// Locate the repo root and proto dir from this test file's location.
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate test file path")
	}
	// thisFile = <repo>/internal/loopwire/v1/drift_test.go
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", "..", ".."))
	protoDir := filepath.Join(repoRoot, "proto")

	tmp := t.TempDir()

	// Write a throwaway buf.gen template whose out dirs all stay UNDER tmp (the
	// committed buf.gen.yaml writes Go via `out: ../`, which would escape a tmp base),
	// with the SAME plugins/options so the regenerated bytes match one-for-one.
	template := "" +
		"version: v2\n" +
		"plugins:\n" +
		"  - local: protoc-gen-go\n" +
		"    out: " + tmp + "/go\n" +
		"    opt:\n" +
		"      - module=github.com/ethanhinson/fuse\n" +
		"  - local: protoc-gen-connect-go\n" +
		"    out: " + tmp + "/go\n" +
		"    opt:\n" +
		"      - module=github.com/ethanhinson/fuse\n" +
		"  - local: [\"npx\", \"protoc-gen-es\"]\n" +
		"    out: " + tmp + "/ts\n" +
		"    opt:\n" +
		"      - target=ts\n" +
		"      - import_extension=js\n"
	tmplPath := filepath.Join(tmp, "buf.gen.drift.yaml")
	if err := os.WriteFile(tmplPath, []byte(template), 0o644); err != nil {
		t.Fatalf("write drift template: %v", err)
	}

	cmd := exec.Command("buf", "generate", "--template", tmplPath)
	cmd.Dir = protoDir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Skipf("buf generate into tmp failed (%v; TS plugin may be uninstalled); output:\n%s", err, out)
	}

	// Compare the committed Go message + connect stubs against the regenerated ones.
	pairs := []struct{ committed, regen string }{
		{
			filepath.Join(repoRoot, "internal", "loopwire", "v1", "loop.pb.go"),
			filepath.Join(tmp, "go", "internal", "loopwire", "v1", "loop.pb.go"),
		},
		{
			filepath.Join(repoRoot, "internal", "loopwire", "v1", "loopv1connect", "loop.connect.go"),
			filepath.Join(tmp, "go", "internal", "loopwire", "v1", "loopv1connect", "loop.connect.go"),
		},
		{
			filepath.Join(repoRoot, "proto", "gen", "ts", "fuse", "loop", "v1", "loop_pb.ts"),
			filepath.Join(tmp, "ts", "fuse", "loop", "v1", "loop_pb.ts"),
		},
	}
	for _, p := range pairs {
		regen, err := os.ReadFile(p.regen)
		if err != nil {
			t.Fatalf("read regenerated %s: %v", p.regen, err)
		}
		committed, err := os.ReadFile(p.committed)
		if err != nil {
			t.Fatalf("read committed %s: %v", p.committed, err)
		}
		if string(regen) != string(committed) {
			t.Errorf("DRIFT: %s differs from `buf generate` output — run `make proto` and commit", p.committed)
		}
	}
}
