// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: fuse/loop/v1/loop.proto

// Package fuse.loop.v1 is the IDL-defined loop.* wire for the networked binding
// (change 0055), successor to the JSON-over-WebSocket wire (#48, ADR-0032
// superseded). It exposes loop control — StartLoop / Send (unary) and Observe
// (server-streaming history-then-live) — as a Connect service so a browser can
// reach it over HTTP/2 with no proxy. Tenant is a typed, pass-through request
// field (identity enforcement is #0049). The per-kind payload shapes are NOT
// re-modeled here: payload stays raw JSON bytes (#50 owns SDK ergonomics), and
// kind stays a string to avoid lock-stepping a proto enum with internal/event.Kind.

package loopv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Interactive   bool                   `protobuf:"varint,4,opt,name=interactive,proto3" json:"interactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoopRequest) Reset() {
	*x = StartLoopRequest{}
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoopRequest) ProtoMessage() {}

func (x *StartLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoopRequest.ProtoReflect.Descriptor instead.
func (*StartLoopRequest) Descriptor() ([]byte, []int) {
	return file_fuse_loop_v1_loop_proto_rawDescGZIP(), []int{0}
}

func (x *StartLoopRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *StartLoopRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StartLoopRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *StartLoopRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

type StartLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLoopResponse) Reset() {
	*x = StartLoopResponse{}
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLoopResponse) ProtoMessage() {}

func (x *StartLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLoopResponse.ProtoReflect.Descriptor instead.
func (*StartLoopResponse) Descriptor() ([]byte, []int) {
	return file_fuse_loop_v1_loop_proto_rawDescGZIP(), []int{1}
}

func (x *StartLoopResponse) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_fuse_loop_v1_loop_proto_rawDescGZIP(), []int{2}
}

func (x *SendRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *SendRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *SendRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_fuse_loop_v1_loop_proto_rawDescGZIP(), []int{3}
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_fuse_loop_v1_loop_proto_rawDescGZIP(), []int{4}
}

func (x *ObserveRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *ObserveRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *ObserveRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// ObserveEvent carries either a domain event or a keepalive/gap marker frame.
type ObserveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`          // unset on a bare keepalive
	Gap           bool                   `protobuf:"varint,2,opt,name=gap,proto3" json:"gap,omitempty"`             // true when a sequence gap preceded this event (re-observe hint)
	Keepalive     bool                   `protobuf:"varint,3,opt,name=keepalive,proto3" json:"keepalive,omitempty"` // true on an idle heartbeat frame (no event); survives idle timeout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveEvent) Reset() {
	*x = ObserveEvent{}
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveEvent) ProtoMessage() {}

func (x *ObserveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveEvent.ProtoReflect.Descriptor instead.
func (*ObserveEvent) Descriptor() ([]byte, []int) {
	return file_fuse_loop_v1_loop_proto_rawDescGZIP(), []int{5}
}

func (x *ObserveEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ObserveEvent) GetGap() bool {
	if x != nil {
		return x.Gap
	}
	return false
}

func (x *ObserveEvent) GetKeepalive() bool {
	if x != nil {
		return x.Keepalive
	}
	return false
}

// Event mirrors internal/event.Event at the transport edge. payload is raw JSON
// (the existing json.RawMessage); kind is a string discriminant.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Depth         int32                  `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	Turn          int32                  `protobuf:"varint,6,opt,name=turn,proto3" json:"turn,omitempty"`
	Kind          string                 `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_fuse_loop_v1_loop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_fuse_loop_v1_loop_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Event) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Event) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_fuse_loop_v1_loop_proto protoreflect.FileDescriptor

const file_fuse_loop_v1_loop_proto_rawDesc = "" +
	"\n" +
	"\x17fuse/loop/v1/loop.proto\x12\ffuse.loop.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\x10StartLoopRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12 \n" +
	"\vinteractive\x18\x04 \x01(\bR\vinteractive\",\n" +
	"\x11StartLoopResponse\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\"T\n" +
	"\vSendRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\"\x0e\n" +
	"\fSendResponse\"\\\n" +
	"\x0eObserveRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\"i\n" +
	"\fObserveEvent\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x13.fuse.loop.v1.EventR\x05event\x12\x10\n" +
	"\x03gap\x18\x02 \x01(\bR\x03gap\x12\x1c\n" +
	"\tkeepalive\x18\x03 \x01(\bR\tkeepalive\"\xd3\x01\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\x12\x12\n" +
	"\x04turn\x18\x06 \x01(\x05R\x04turn\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload2\xe1\x01\n" +
	"\vLoopService\x12L\n" +
	"\tStartLoop\x12\x1e.fuse.loop.v1.StartLoopRequest\x1a\x1f.fuse.loop.v1.StartLoopResponse\x12=\n" +
	"\x04Send\x12\x19.fuse.loop.v1.SendRequest\x1a\x1a.fuse.loop.v1.SendResponse\x12E\n" +
	"\aObserve\x12\x1c.fuse.loop.v1.ObserveRequest\x1a\x1a.fuse.loop.v1.ObserveEvent0\x01B9Z7github.com/ethanhinson/fuse/internal/loopwire/v1;loopv1b\x06proto3"

var (
	file_fuse_loop_v1_loop_proto_rawDescOnce sync.Once
	file_fuse_loop_v1_loop_proto_rawDescData []byte
)

func file_fuse_loop_v1_loop_proto_rawDescGZIP() []byte {
	file_fuse_loop_v1_loop_proto_rawDescOnce.Do(func() {
		file_fuse_loop_v1_loop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fuse_loop_v1_loop_proto_rawDesc), len(file_fuse_loop_v1_loop_proto_rawDesc)))
	})
	return file_fuse_loop_v1_loop_proto_rawDescData
}

var file_fuse_loop_v1_loop_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_fuse_loop_v1_loop_proto_goTypes = []any{
	(*StartLoopRequest)(nil),      // 0: fuse.loop.v1.StartLoopRequest
	(*StartLoopResponse)(nil),     // 1: fuse.loop.v1.StartLoopResponse
	(*SendRequest)(nil),           // 2: fuse.loop.v1.SendRequest
	(*SendResponse)(nil),          // 3: fuse.loop.v1.SendResponse
	(*ObserveRequest)(nil),        // 4: fuse.loop.v1.ObserveRequest
	(*ObserveEvent)(nil),          // 5: fuse.loop.v1.ObserveEvent
	(*Event)(nil),                 // 6: fuse.loop.v1.Event
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_fuse_loop_v1_loop_proto_depIdxs = []int32{
	6, // 0: fuse.loop.v1.ObserveEvent.event:type_name -> fuse.loop.v1.Event
	7, // 1: fuse.loop.v1.Event.ts:type_name -> google.protobuf.Timestamp
	0, // 2: fuse.loop.v1.LoopService.StartLoop:input_type -> fuse.loop.v1.StartLoopRequest
	2, // 3: fuse.loop.v1.LoopService.Send:input_type -> fuse.loop.v1.SendRequest
	4, // 4: fuse.loop.v1.LoopService.Observe:input_type -> fuse.loop.v1.ObserveRequest
	1, // 5: fuse.loop.v1.LoopService.StartLoop:output_type -> fuse.loop.v1.StartLoopResponse
	3, // 6: fuse.loop.v1.LoopService.Send:output_type -> fuse.loop.v1.SendResponse
	5, // 7: fuse.loop.v1.LoopService.Observe:output_type -> fuse.loop.v1.ObserveEvent
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fuse_loop_v1_loop_proto_init() }
func file_fuse_loop_v1_loop_proto_init() {
	if File_fuse_loop_v1_loop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fuse_loop_v1_loop_proto_rawDesc), len(file_fuse_loop_v1_loop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fuse_loop_v1_loop_proto_goTypes,
		DependencyIndexes: file_fuse_loop_v1_loop_proto_depIdxs,
		MessageInfos:      file_fuse_loop_v1_loop_proto_msgTypes,
	}.Build()
	File_fuse_loop_v1_loop_proto = out.File
	file_fuse_loop_v1_loop_proto_goTypes = nil
	file_fuse_loop_v1_loop_proto_depIdxs = nil
}
